### PR TITLE
Speed up transfers

### PR DESCRIPTION
**Pull request by ducasp**
Hi fr3nd,

I've made a few changes that speed up a lot file transfers. On my UNAPI adapter, it went from 2,7KB/s average to almost 20KB/s average.

Best regards,

Oduvaldo

### CODE REVIEW

**Comment by fr3nd** [comment]
Thank you!! It looks promising. I'm currently unable to review your contribution, but I'll do it as soon as possible!

**Comment by ducasp** [comment]
Hi fr3nd,

I have made a small fix, where some hub packages were not working on my improved speed version of MSX HUB because it would loop filling the screen with the progress bar when a file with too small size was received (i.e.: sofarun has a bas file of 27 bytes and trying to hub install it in 80 columns would not be succesfull). This version seems to be quite stable and I've tested it with many packages with success. :)

**Comment by fr3nd** [comment]
Wow, that's a huge improvement. The speed increase is really noticeable and so far I haven't detected any issue.

I'd like to do some more testing before merging your PR and releasing a new version, but it looks really good!

Thank you for your contribution!

**Comment by fr3nd** [comment]
I did some small and cosmetic changes to your code in #9 and I merged it. Awesome work, thank you! 🥇 
I'll create a new release now.

**Comment by ducasp** [comment]
Glad to help! 🙂

**Pull request merged**
